language: haskell
ghc:
  - 7.6
  - 7.8

install:
  - cabal sdist --output-directory playpen
  - cd playpen
  - cabal install --only-dependencies --enable-tests
  - ghc-pkg list


script:
  - pwd
  - cabal install packdeps
  - packdeps matchers.cabal
  - cabal install
